### ISSUE TITLE
Duplicate of Hekimoğlu 'Alī Paşa MS 574/2

### ISSUE THREAD

**Issue by ahankinson** [bodleian/fihrist-mss#10]
If you search for "Hekimoğlu" you get three records:

http://fihrist-qa.bodleian.ox.ac.uk/?utf8=%E2%9C%93&q=Hekimo%C4%9Flu

There are three TEI files for this one MSS in the "arabic commentaries" folder. Can this be resolved so that we have just one record for this MSS?

**Comment by eifionjones** [comment]
Deduplicated files to best record
