### ISSUE TITLE
Sometimes physical form is repeated in the index

### ISSUE THREAD

**Issue by ahankinson** [bodleian/fihrist-mss#13]
If you go to http://fihrist-qa.bodleian.ox.ac.uk/?f%5Btype%5D%5B%5D=manuscript and choose to filter by "Physical form" you will see some repeated values ('codex codex').

Multiple identical values should be collapsed into a single value, keeping in mind that you might have multiple physical forms in a single MSS.

**Comment by andrew-morrison** [comment]
I assume the physDesc/objectDesc/@form that is wanted is the one that pertains to the msDesc and not the msPart children. Or should multiple output "ms_physform_s" elements be outputted, in case there ever are parts with different physical forms to the manuscripts? Seems unlikely, but I need to familiarize myself with the schema.

**Comment by ahankinson** [comment]
I think there should be multiple form types possible on a record, so multiple `ms_physform_s` field should be output. (There may be a case, for example, where a record contains both 'codex' and 'leaf' forms in the parts.)

**Comment by andrew-morrison** [comment]
So, the aim is output Solr docs which look something like...

`<field name="ms_physform_sm">codex</field>
<field name="ms_physform_sm">leaf</field>
`

...when/if there are multiple different values, and...

`<field name="ms_physform_s">codex</field>
`

...when that's the only distinct value in the source TEI document.

I'll get on it when I've got a local repository set up to be able to develop and test a fix.

**Comment by ahankinson** [comment]
It would be ms_physform_sm for all of them, even if there's only one value. This is because the facet field in Blacklight will be configured to look at values in ms_physform_sm
