### ISSUE TITLE
provide fuller css for previewManuscript

### ISSUE THREAD

**Issue by holfordm** [bodleian/fihrist-mss#14]
This may not be a high priority, especially if it is technically difficult, but previewManuscript would be even more useful if it could import the css used by Blacklight, so that the formatting of the record is even closer to how it will finally appear.

**Comment by andrew-morrison** [comment]
It should be using the CSS from the live site. But the URL looks like it might break, possibly every time the site is updated.

**Comment by ahankinson** [comment]
The CSS is (unhelpfully) compiled from SCSS by Rails at runtime, with some special Rails magic to point to image assets, etc.

You can find that here: https://gitlab.bodleian.ox.ac.uk/TEI-consolidation/medieval-mss-search/tree/master/app/assets/stylesheets

As it doesn't change very often you might just copy and paste the output CSS from the site into a local file and use that.

**Comment by andrew-morrison** [comment]
I've done my best to pick out the more relevant styles from the thousands of lines of CSS (which do all kinds of ancillary stuff like the on-screen keyboard in the search box on the web sites.)

It doesn't look precisely the same, but at least things that are bold or italic on the web site should be likewise when previewing (which, for reasons unknown, simply importing the entire CSS from the web site doesn't do.)

I've committed the change to the medieval-mss repository, now doing the same for Fihrist (the CSS may diverge in the future, but for now I've used the same.)
