### ISSUE TITLE
Set up Fihrist with manuscripts HTML view

### ISSUE THREAD

**Issue by andrew-morrison** [bodleian/fihrist-mss#15]
This will involve:

- Setting up the Bash and XQuery processing scripts
- Configuring Blacklight on fihrist-qa with most of the same indexes and HTML view as Medieval
- Writing documentation (part of bodleian/consolidated-tei-schema#3)
- Ensuring @eifionjones is happy with the process

Aim to get this working around the middle of next week.

**Comment by andrew-morrison** [comment]
The [Fihirst QA site now has manuscripts](http://fihrist-qa.bodleian.ox.ac.uk/?f%5Btype%5D%5B%5D=manuscript) with:
- HTML views of each, using the same XSL as Medieval, plus [one customization](https://github.com/bodleian/fihrist-mss/commit/b14e51326bbff504b1c11567d61f56aed8a05a5f) which I've just added as an example. There are a lot of basic display issues, many of which seem to be the result of the way the manuscript descriptions have been (I assume) batch converted. For example there are many instances of person name, work titles, dates, references, etc, which are missing leading and trailing spaces in the TEI, so they run into, or on from, adjacent words in the HTML. Also, I believe there are changes to the CSS coming soon. All of which makes it difficult to know what should and shouldn't be fixed in the XSL.
- Search filters for:
	- Language - probably needs review to consolidate some of the values 
	- Physical form
	- Century - is another filter needed for Islamic dates?
	- Materials
	- Institution
	- Collection - some issues with consistency in the data
- The above is generated by scripts which I have now added to the fihrist-mss repository. So, @eifionjones, if you have access to our solr01-qa.bodleian.ox.ac.uk server you should be able to re-build the HTML and Solr indexes yourself.

What's missing:

- Authority files for people, works and libraries. Hence trying to re-index those won't work.
- Design changes (straplines, logos, etc.)
- Access to the QA site for other people who need to see it.
- A feedback/access-request link, as on the old web site.
- Instructions and templates for contributors.

Sorry it has taken longer than I thought to get this far. Hopefully, now that I am more familiar with the sort of issues that arise with these TEI catalogues, I can prioritize a bit better in the New Year.

**Comment by eifionjones** [comment]
Great, many thanks for this Andrew! I'll get onto it in the New Year.

**Comment by andrew-morrison** [comment]
Any feedback, [especially about the documentation](https://github.com/bodleian/consolidated-tei-schema/issues/3), is welcome.

**Comment by andrew-morrison** [comment]
I have made a small change today. Now the [manuscripts search on the Fihrist QA site](http://fihrist-qa.bodleian.ox.ac.uk/?f%5Btype%5D%5B%5D=manuscript) returns "Not Specified" in each filter for the TEI descriptions that lack the necessary information.

The way I have implemented this it is easy to switch on or off. Like Medieval, you may not want this when the site is launched, but I thought it useful at this stage to highlight some of the issues in the data.

Note that for Materials there already is a value of "Unknown" to which 70 of the manuscripts belong. That is different - they contain a `supportDesc` field with a `@material` attribute set to "unknown". Which is why I chose "Not specified" so the 67 manuscripts that have not been catalogued with a `supportDesc/@material` are revealed.

The biggest issue appears to be dates. In the Century filter there are 6347 manuscripts which don't have an `origin/origDate` specifying the date in the Gregorian calendar, or at least not one formatted in the way I expected from Medieval (but presumably validate according to the schema.) I think there are going to be a lot of issues with inconsistency in the formatting of dates, some needing modifications to the indexing script, some fixing in the data. So I'll create a new issue for those.

**Comment by andrew-morrison** [comment]
Sorry, I tagged this issue into a commit yesterday by mistake. Re-closing.
