### ISSUE TITLE
Is a status attribute needed on TEI documents?

### ISSUE THREAD

**Issue by andrew-morrison** [bodleian/fihrist-mss#16]
Raising this here, because it is likely to be a particular issue for Fihrist with its many contributors, but it's an issue for all catalogues.

Should the indexing processing look for a status attribute, perhaps [this one on the revisionDesc element](http://www.tei-c.org/release/doc/tei-p5-doc/en/html/ref-att.docStatus.html), and only index TEI descriptions that are "published"?

That would provide a mechanism for people to edit a description file and push it to GitHub without fear of it appearing on their catalogue's web site until they change the status to "published".

**Comment by holfordm** [comment]
Interesting idea! My initial questions:
1. would this meet a real user need - would people want to have drafts in the central repo rather than just on their local machines? (and should we encourage this?)
2. if it is a need, is this the best way of doing it? is there a danger of the human cataloguers losing track of drafts / finished descriptions if they are all in the same place? Would a separate directory "drafts" be an alternative solution?

**Comment by andrew-morrison** [comment]
Perhaps this is something to consider, but hold off doing anything unless/until a need arises?

I was thinking ahead while writing some [instructions for cataloguers](https://github.com/bodleian/consolidated-tei-schema/wiki/Editing-TEI-files#editing-tei-manuscript-descriptions). If we start getting emails from contributors saying, "I accidentally committed such-and-such before I was finished, please can you remove it from the web site", then it might be worthwhile. But you are right that imposing it now risks situations where people have to find and edit other people's files, because they forgot to switch the status to "published" before going on holiday, or changing jobs.

Drafts subfolders are also possible, and would make things a bit more obvious, although I think Git treats moving a file as two separate events, a deletion and a creation, probably starting a new history of changes.

**Comment by eifionjones** [comment]
I agree re: leaving it on the back burner for now. It's a good idea, but as Matthew says cataloguers might prefer to work locally and "publish" by pushing to GitHub
