### ISSUE TITLE
Tidy up fihrist-mss files

### ISSUE THREAD

**Issue by andrew-morrison** [bodleian/fihrist-mss#18]
I just tried to clone the fihrist-mss repository on a Windows system and it failed. It worked fine previously on Linux. The reason is characters in filenames that are illegal on Windows (I think asterisks, but as they cannot be created I can only go by what the error messages said.)

I think these are only found in the 'working' folder, which the readme says, "contains the working files before and after conversion".

@eifionjones, @ahankinson: Is there any need for this working folder any longer? If not, can I delete it? Maybe git-rm it, if no record for previous conversions are needed?

**Comment by ahankinson** [comment]
I would be OK with deleting it, so long as we're sure that all of the information was transferred correctly in James' migration scripts.

**Comment by eifionjones** [comment]
Is it ok to take it out of this repository but keep it somewhere just in case? It would be good to have a copy of the original data just in case

**Comment by andrew-morrison** [comment]
If there is a reason to keep them, then GitHub is the best place.

Has all work on the 'working' folder been completed and everything is now in 'collections'?

If so, I can replace the 'working' folder with a compressed archive file. It'd be a 30MB binary file, but as long as nobody is going to need to edit it, it shouldn't be a problem. And it would allow people on Windows to clone the repository, which they'll need to do before they can edit the descriptions.

**Comment by eifionjones** [comment]
All work is completed in 'working' but it's useful sometimes for me as a reference in terms of what happened in the conversion. Instead of clogging up the GitHub repository, maybe I should make a copy and archive it here - it won't be of any use to people editing the data and may confuse them
