### ISSUE TITLE
People button (person index)

### ISSUE THREAD

**Issue by andrew-morrison** [bodleian/fihrist-mss#19]
This is now working on QA: http://fihrist-qa.bodleian.ox.ac.uk/?f%5Btype%5D%5B%5D=person

Starting this issue to discuss the processes behind this and changes Fihrist might need.

**Comment by andrew-morrison** [comment]
As mentioned in an earlier email conversation, the person index is built from an authority file which:

- Stores decisions on which version of a person's name to display because the web site has no memory of such choices: everything is wiped and re-indexed every time.
- Brings alternative forms of names together to they can be indexed for the same person.
- Could be used in the future to expand the pages for each person (e.g. links to VIAF, Wikidata, etc)

I've written a script to scan all the manuscript descriptions and build an authority file. It makes the following assumptions:

- Every person who should be indexed has been marked up in a `persName`, `author` or `name` element with a `@key` attribute (name elements are used for other things, so those must contain a `persName` to be included).
- When there are two or more `persName` elements inside an `author` or `name` element then those are treated as alternative forms of the same person's name (and the `@key` of the parent element is used).
- The longest version of a name is chosen for display, on the basis it probably has the most information (like dates of birth and/or death), but that might be favouring Latinized versions.

43% of the people found have more than one variation of their name. The script makes no attempt to combine the same or similar names recorded in the manuscripts with different `@key` values (e.g. three of the four returned [by this search](http://fihrist-qa.bodleian.ox.ac.uk/?utf8=%E2%9C%93&f%5Btype%5D%5B%5D=person&q=Bevan).)

I have committed that authority file to GitHub. It is a single big file but it could be split into separate files for each project partner, based on whose manuscripts each person is primarily mentioned in. You can open _authority/persons_master.xml_ in Safari, Firefox or IE and it'll display them with all the variants that are indexed but not displayed on the web site. If you open in Oxygen there are comments for each giving an example of a manuscript they are in. Changing the `@type` of a `persName` to "display" will set that as the one to be used on the web site. But if you don't think this will be manageable, I could set up the script to rebuild that authority file every time you want to re-index.

**Comment by eifionjones** [comment]
This looks great - I think we will look to fix variant names in the data rather than manually curate the authority file if that works ok.

**Comment by andrew-morrison** [comment]
Regarding indexing, that takes the authority file and maps it to the fields set up in the Solr search engine. That's when the facets are generated:

- Alphabetical index: This is the first character the displayed name, indexed separately to allow browsing alphabetically. But without manual curation of the authority list, for some people that is the first letter of their surname and in other cases their first initial. The XML parser seems to have been intelligent enough to read right-to-left for Arabic script, but whether it makes sense for Islamic names to browse this way, I don't know.
- Roles: These are taken from the `@role` attributes in the manuscript descriptions, but few have those, so the following are inferred from their location in the TEI document:
	- Author: the person is mentioned in, or is marked up as, an `author` element. 
	- Subject: the person is mentioned in the `title` or an `msItem`. This might work better for some kinds of manuscripts than for others, so let me know if you want to keep this or not.

**Comment by andrew-morrison** [comment]
I will rebuild this index with similar deduplication to works (#21) and split the authority file into persons_additions.xml and persons_curated.xml as discussed.

**Comment by andrew-morrison** [comment]
I've rebuilt the Person index. I experimented with ignoring the `@key` values already in the source TEI, and using similar pattern matching as in the works index to create new ones, but I decided too much valuable information would be lost. That does mean I couldn't automatically deduplicate simple punctuation differences, such as all the different ways [anonymous authors](http://fihrist-qa.bodleian.ox.ac.uk/?f%5Bpp_roles_sm%5D%5B%5D=Author&f%5Btype%5D%5B%5D=person&q=anonymous) have been catalogued. These can be manually deduplicated, I'll write instructions on how to do so soon.

Some improvements include separating out the person's name in another language when marked up with `foreign` tags and indexing (but not displaying) those as variants. And I've changed the selection of which variant form to display so it is now whichever is the most popular version throughout all the collections (rather than the length.) But that can be manually overridden in the authority file too.

There are more values in the Roles facet, mostly coming from `@role` attributes on `editor` elements. Some of these need mapping to something more meaningful (e.g. "Trl" possibly means translator?) and merging (e.g. "Compilator" into "Compiler"). Some look like typos (e.g. "Copiler", "Transtator") which will need fixing in the TEI.

**Comment by andrew-morrison** [comment]
I'm closing this issue as the basic person index is [up and working](http://fihrist-prd.bodleian.ox.ac.uk/?f%5Btype%5D%5B%5D=person), and the scripts and authority files are in place to be able to re-index as and when the data is improved. For example, the values in the "Role" facet are all taken from the TEI files, so that is where the typos need to be fixed.

Please raise a new issue for any change requests (e.g. if you want to merge two role vales, say "Abridger" and "Reviser", that would be a script change, or the rules for what is considered a letter in the "Limit your search by letter".)
