### ISSUE TITLE
Subject index/button

### ISSUE THREAD

**Issue by andrew-morrison** [bodleian/fihrist-mss#20]
The other index you identified as wanting to include before launch was subjects.

I assume these should to be extracted from `term` elements with `@key` attributes?

I can find 1937 distinct IDs for those, with a maximum of 8 different variant forms for any one. All have a `@target` referencing a Library of Congress authority entry.

As with people, without a local authority file, there won't be a way to select which variant to display on the web site. For example, "sh90001470" appears as "Mundane astrology" in three manuscript descriptions and as "Judicial astrology" in another three. There is nothing really to choose between them. Both will be indexed but only one can be displayed in the search results. Technically it would be possible to go and lookup which the LOC has chosen to prefer ([its the former](http://id.loc.gov/authorities/subjects/sh90001470.html)) but that would require a lot of development work for little gain (their choice might not always be the best for our material.)

@eifionjones: Unless you have any suggestions or requests for how to handle these, I'll go ahead and set this up the best I can when I am next free to work on Fihrist.

**Comment by eifionjones** [comment]
Hi Andrew, all sounds good. It's fine for you to go ahead and set it up in the best way you can - if nothing else, just choose the first term. It sounds like this is something which really needs to be fixed in the data

**Comment by andrew-morrison** [comment]
I have implemented a first draft of a subject index on the Fihrist QA site: http://fihrist-qa.bodleian.ox.ac.uk/?f%5Btype%5D%5B%5D=subject

The "Subject Types" facet contains the only two options possible at the moment: whether the subject is a place (i.e. in the TEI it is either a `placeName` element or a `name` element with a `@type` of "place") or Library of Congress Subject Heading (i.e. a `term` with a `@ref` attribute pointing to a loc.gov URI). 19 overlap the two (probably more places that those are in LCSH, but they haven't been looked up and refs added to the TEI.)

It could really do with more options in the facet to allow people to drill down, but that would require a systematic review of the authority file, adding an appropriate level of broader terms, and linking them somehow (perhaps with `@corresp` attributes). I don't have the subject knowledge (or time) to do that.

There are duplicates, but these seem to be legitimately different entries in LCSH. For example, the top two hits for [this search](http://fihrist-qa.bodleian.ox.ac.uk/?f%5Btype%5D%5B%5D=subject&q=Anecdotes) correspond to [this](http://id.loc.gov/authorities/subjects/sh85004931.html) and [this](http://id.loc.gov/authorities/subjects/sh99001294.html), so both are valid, as are the six other narrower terms. These can be manually deduplicated, I'll write instructions for how soon.

There are lots of `term` and `placeName` elements in the source TEI without `@key` attributes, so do not appear in this index. I'll modify the script I've written so that it can update the authority file as and when new keys are added after launch.

**Comment by andrew-morrison** [comment]
I've renamed the "Subject Types" facet to the "Classification" to better fit with the others when a generic search is performed.

I'm closing this issue as the basic subject index is [up and working](http://fihrist-prd.bodleian.ox.ac.uk/?f%5Btype%5D%5B%5D=subject), and the scripts and authority files are in place to be able to re-index as and when the data is improved. Please raise a new issue for any changes (e.g. renaming the facet or any of its options.)
