### ISSUE TITLE
Fix missing space

### ISSUE THREAD

**Issue by andrew-morrison** [bodleian/fihrist-mss#23]
As mentioned in #15, pretty much any part of a manuscript description that marks up elements inline in the middle of sentences (such as when a `persName` is used to tag a person mentioned in a work title) has lost spaces around the tags somewhere along the line.

For example this...

`<title>Copy of a document dated 15 Aug. 1615 requesting safe conduct for one<persName xml:lang="ar-Latn-x-lc" key="person_f4390">Yāmīn ibn Rammawkh</persName>merchant of<placeName>Fez</placeName>while trading in Europe. [Transcripts by<persName key="person_f4347">Wm. Bedwell</persName>of the Arabic and Spanish originals, with translations by him of both.]</title>`

...is displaying as...

_Copy of a document dated 15 Aug. 1615 requesting safe conduct for oneYāmīn ibn Rammawkhmerchant ofFezwhile trading in Europe. [Transcripts byWm. Bedwellof the Arabic and Spanish originals, with translations by him of both.]_

...so it needs to be transformed into this...

`<title>Copy of a document dated 15 Aug. 1615 requesting safe conduct for one <persName xml:lang="ar-Latn-x-lc" key="person_f4390">Yāmīn ibn Rammawkh</persName> merchant of <placeName>Fez</placeName> while trading in Europe. [Transcripts by <persName key="person_f4347">Wm. Bedwell</persName> of the Arabic and Spanish originals, with translations by him of both.]</title>`

...so it looks like this...

_Copy of a document dated 15 Aug. 1615 requesting safe conduct for one Yāmīn ibn Rammawkh merchant of Fezwhile trading in Europe. [Transcripts by Wm. Bedwellof the Arabic and Spanish originals, with translations by him of both.]_

I've got the XSL to fix this ready to go. I'll run it along with fixing date issues #17.

**Comment by ahankinson** [comment]
I would suggest running them separately and committing each change, as you may need to roll back one individually?

**Comment by andrew-morrison** [comment]
No issues with added space reported, so closing this issue.
