### ISSUE TITLE
Limit your search by letter

### ISSUE THREAD

**Issue by andrew-morrison** [bodleian/fihrist-mss#24]
Is there some Blacklight or front-end setup task needed to get the "Alphabetical Index" facet on, for example, Fihrist's People search...

http://fihrist-qa.bodleian.ox.ac.uk/?f%5Btype%5D%5B%5D=person

...to display at the top as "Limit your search by letter" rather than on the left-hand side, as on Medieval...

 http://medieval-qa.bodleian.ox.ac.uk/?f[type][]=person

Presumably whatever it is needs to be done for all catalogues, whenever an index has an 'alpha_title' field?

**Comment by IgnatG** [comment]
//implemented
