### ISSUE TITLE
Setup 404 page to handle old fihrist.org.uk URLs

### ISSUE THREAD

**Issue by andrew-morrison** [bodleian/fihrist-mss#29]
Only for manuscripts. So, for example, this...

http://www.fihrist.org.uk/profile/manuscript/25c55774-06bd-45d0-987e-23234692a1e1

...would ideally redirect to this...

http://www.fihrist.org.uk/catalog/manuscript_29

...which, after launch, will serve this page...

http://fihrist-qa.bodleian.ox.ac.uk/catalog/manuscript_29

@ahankinson: Can this be done in NGINX as rewrite rules?

Alternatively, can the text of the 404 page be changed to explain that the site has been redeveloped, and link to the home page for people to search?

**Comment by ahankinson** [comment]
Unfortunately it cannot be done. We don't have the link between the old UUID and the new manuscript ID, so we don't know that `25c5...` is `manuscript_29`. (I think the UUID was re-generated every time the site was indexed, as well, so it's quite an ephemeral identifier. :-/ )

You can create a 404 page by adding a 404.html file to the 'public' directory of the rails application, and then importing the styling, etc. You should probably do that for each of the TEI catalogue sites.

**Comment by holfordm** [comment]
issue #86 https://github.com/bodleian/medieval-mss/issues/86 on medieval mss covers the same ground

**Comment by andrew-morrison** [comment]
Implemented by @ahankinson
