### ISSUE TITLE
Fihrist About and Help pages

### ISSUE THREAD

**Issue by andrew-morrison** [bodleian/fihrist-mss#30]
Copy the existing web site's text (http://www.fihrist.org.uk/about and http://www.fihrist.org.uk/help) to begin with, Yasmin to write new text.

**Comment by IgnatG** [comment]
//implemented

**Comment by andrew-morrison** [comment]
Reopening as reminder that new text is needed for the about and help pages.

**Comment by andrew-morrison** [comment]
The web site has gone live with updated help and about pages so closing this issue. The wording can be tweaked as and when desired (but, unfortunately, those files are in the Blacklight configuration, held in our internal repositories, not on here, so it has to be done via requests by email.)
