### ISSUE TITLE
Feedback link

### ISSUE THREAD

**Issue by andrew-morrison** [bodleian/fihrist-mss#32]
The old web site has "You can comment on this record here." at the bottom of all pages, linking to a contact form, with the "To" and "Subject" fields set to the email address of the owner institution and the classmark of the manuscript respectively.

The ideal solution would be to adapt the current contact form to do that. @IgnatG may have some code he can reuse from another project.

Alternatively, get all the partner organizations to edit their `additional/adminInfo/availability` fields to include a link to their own contact pages on their own web sites. These need review anyway for outdated information. The classmark won't be passed on, but we could setup the XSL so these open in a new tab, so users can switch back to be able to copy and paste more easily. Note that Arabic Commentaries on the Hippocratic Aphorisms project and Wellcome Trust do not currently have any availability field (and the latter has no email address in the `publicationStmt` either, which is why the comment links on the old web site [don't work for their manuscripts](http://www.fihrist.org.uk/comment/index?type=manuscript&id=3ecf4213-b720-4a33-83ab-685accddc37b).) @eifionjones: Is this something you can get started?

**Comment by IgnatG** [comment]
//implemented. 
See below how it renders. 
Currently, it sends all emails to me. I'll open another issue where we can discuss more about it. 


![email](https://user-images.githubusercontent.com/6107088/36305930-92b5bbe2-130d-11e8-842c-d68669141197.png)
![form](https://user-images.githubusercontent.com/6107088/36305931-92cbf04c-130d-11e8-850f-fcfd345ad618.png)

**Comment by andrew-morrison** [comment]
This has been deployed to the Fihrist QA site, if you want to take a look @eifionjones. For example: http://fihrist-qa.bodleian.ox.ac.uk/catalog/manuscript_990

It needs to be changed so the link only appears on manuscript pages. Elsewhere, there is no clear "ownership" of the information on the page.

Also, the full name field is optional here, but required on the [contact form page](http://fihrist-qa.bodleian.ox.ac.uk/contact). I'd say the latter is correct seeing as the email address is required.

**Comment by andrew-morrison** [comment]
Also, could the href of the feedback link be changed from "#" to "/contact" then at least that would work as a backup.

**Comment by IgnatG** [comment]
Nop. If I do that, there won't be any pop-ups
