### ISSUE TITLE
Email addresses on comments

### ISSUE THREAD

**Issue by IgnatG** [bodleian/fihrist-mss#35]
Currently the -Comment on this record- feature sends all emails to me. 
I assume that different records would have different email addresses - depending who's the owner
In which case, I'll need:
a) A list of all emails - maybe from @eifionjones. It would be better if you could send it to me via email
b) A field on the page which could tell me where to send it to. - maybe from @andrew-morrison 

#32

**Comment by andrew-morrison** [comment]
(a) As noted in issue #32, we have email addresses for all except Wellcome Trust stored in the TEI files. Assuming we don't want to be passing those around on the client-side, we could convert the list into MD5 or SHA sums, and have a lookup table in both the XSL and the server-side code. The latter would need a default address (same as the one used by the [contact form page](http://fihrist-qa.bodleian.ox.ac.uk/contact) presumably) in case those ever change (and for comments about Wellcome Trust manuscripts.)

(b) What do you mean by "a field on the page"?

**Comment by IgnatG** [comment]
b) I need to know which record belongs to whom. I'm not sure this can be done directly server side -I don't know a way -**yet**- to do that. 
a) I don't have access to that file/list of emails.

**Comment by andrew-morrison** [comment]
If I index the email addresses in a Solr field called, say, `ms_contactemail_sni`, will you be able to pick that up and use it to send emails, all on the server-side?

There will need to be a hardcoded default address for the 94 manuscripts which contain no email address in their TEI.

**Comment by IgnatG** [comment]
that should work - I hope

**Comment by IgnatG** [comment]
@andrew-morrison for manuscripts that don't have the email address we won't show the comments form - just confirmed this with Yasmin. 
I'll need a field in the database that tells me whether a record has an email address or not - a flag maybe (true/false). Is this doable?

**Comment by ahankinson** [comment]
Can you just test whether an e-mail address is present? 

```
if not email_address: do not show form
else if email_address: show form
```

**Comment by IgnatG** [comment]
good point

**Comment by ahankinson** [comment]
I just committed a fix to the Rails app that should address this.
