### ISSUE TITLE
Duplicate manuscripts

### ISSUE THREAD

**Issue by andrew-morrison** [bodleian/fihrist-mss#36]
I've found the following TEI files that appear to be describing the same manuscript, in the same collection, but the files got duplicated at some point:

british library/Or_14841A.xml: http://fihrist-qa.bodleian.ox.ac.uk/catalog/manuscript_5715
british library/Or_14841_A.xml: http://fihrist-qa.bodleian.ox.ac.uk/catalog/manuscript_5714

british library/IO_Islamic_2818.xml: http://fihrist-qa.bodleian.ox.ac.uk/catalog/manuscript_3544
british library/IOIslamic2818.xml: http://fihrist-qa.bodleian.ox.ac.uk/catalog/manuscript_3590

british library/IOIslamic3099.xml: http://fihrist-qa.bodleian.ox.ac.uk/catalog/manuscript_3591
british library/IO_Islamic_3099.xml: http://fihrist-qa.bodleian.ox.ac.uk/catalog/manuscript_3553

british library/IOIslamic3207.xml: http://fihrist-qa.bodleian.ox.ac.uk/catalog/manuscript_3592
british library/IO_Islamic_3207.xml: http://fihrist-qa.bodleian.ox.ac.uk/catalog/manuscript_3554

british library/IOIslamic3456.xml: http://fihrist-qa.bodleian.ox.ac.uk/catalog/manuscript_3593
british library/IO_Islamic_3456.xml: http://fihrist-qa.bodleian.ox.ac.uk/catalog/manuscript_3560

british library/IOIslamic4836.xml: http://fihrist-qa.bodleian.ox.ac.uk/catalog/manuscript_3594
british library/IO_Islamic_4836.xml: http://fihrist-qa.bodleian.ox.ac.uk/catalog/manuscript_3580

One of each pair should be deleted, but which?

@eifionjones: Do you know who to contact at the BL?

**Comment by eifionjones** [comment]
Hi Andrew - don't worry, I'll sort this out

**Comment by eifionjones** [comment]
Duplicate files deleted

**Comment by andrew-morrison** [comment]
I've updated the web site to remove those manuscripts from the index (and links to them from works, people and subjects.)
