### ISSUE TITLE
Logos & Partners

### ISSUE THREAD

**Issue by IgnatG** [bodleian/fihrist-mss#38]
Would it be possible to check if the logos at the bottom of the page are the correct ones? - currently I took those from their website but I'm not sure if they are happy with them or if I have to use different ones.

Also, for each partner I've added a redirect to their website (in a new tab). Could you check to see if the page is the correct one?

**Comment by andrew-morrison** [comment]
Yasmin asked on the Fihrist mailing list for people to check their logos, a few weeks ago, and nobody has complained, so I think this issue can be closed.
