### ISSUE TITLE
CSS to put faint grey lines lines between each work

### ISSUE THREAD

**Issue by andrew-morrison** [bodleian/fihrist-mss#42]
Fihrist doesn't have as many manuscripts containing long lists of works as some other catalogues, but for the [rare cases where it does](http://fihrist-qa.bodleian.ox.ac.uk/catalog/manuscript_1807), I think it would be worth adding the CSS to put a faint grey line between each div of class "msItem", to make it easier to scan down and find the one you're looking for. 

Basically re-implement the fix for bodleian/hebrew-mss#4 in Fihrist.

In fact, can the same thing be copied across to all the TEI catalogues yet to come?

**Comment by IgnatG** [comment]
done
