### ISSUE TITLE
Heading for listBibl within msItem

### ISSUE THREAD

**Issue by eifionjones** [bodleian/fihrist-mss#45]
Could we have entries for un-typed listBibl/bibl within msItem given the header "References:" - e.g. 

http://fihrist-qa.bodleian.ox.ac.uk/catalog/manuscript_9002

**Comment by andrew-morrison** [comment]
I'm marking this a bug because these are pretty confusing without a header, so this should probably be done before launching.

**Comment by andrew-morrison** [comment]
This is now on the QA site. I've tried to choose between using a `h3` or a `h4` for the "References" heading based on context, but it may not be work ideally in all cases. Here are some examples:

http://fihrist-qa.bodleian.ox.ac.uk/catalog/manuscript_4029
http://fihrist-qa.bodleian.ox.ac.uk/catalog/manuscript_1942
http://fihrist-qa.bodleian.ox.ac.uk/catalog/manuscript_1943
http://fihrist-qa.bodleian.ox.ac.uk/catalog/manuscript_9347
http://fihrist-qa.bodleian.ox.ac.uk/catalog/manuscript_3123
http://fihrist-qa.bodleian.ox.ac.uk/catalog/manuscript_8122

Where one msItem stops and the next one starts (or where there are child msItems) has been made clearer by #42 which has just been implemented too and deployed to QA.

I'd like to deploy to fihrist-prd.bodleian.ox.ac.uk later today, so everyone can see the changes, but we're halfway through implementing #35 as well.

**Comment by eifionjones** [comment]
Looks good to me! Thanks

**Comment by andrew-morrison** [comment]
I think bibliographic references could be handled better in the XSL, and it would be better if the links to digitized copies where semantically marked up as such, but I'm closing this particular issue as it looks good enough for launch.
