### ISSUE TITLE
Summary of Contents field in MSS view

### ISSUE THREAD

**Issue by ahankinson** [bodleian/fihrist-mss#48]
(with apologies for the contents of the record 😊 )

https://www.fihrist.org.uk/catalog/manuscript_10135

In the HTML version of the record the summary reflects the title, but truncated in length. I'm wondering if we need to show the summary of contents in the HTML record.

**Comment by andrew-morrison** [comment]
I thought about hiding the constructed summaries in the HTML view, but there are ~15% of manuscripts that already had manually-created summaries. Hiding those would mean losing something useful, and only hiding the constructed ones would be inconsistent.

These particular constructed summaries, which are simply truncated copies of the titles, aren't very helpful. Nor are the ones that are just "X works by Y authors". Thinking about it again, what might be more informative, and less repetitive, would be to use LoC subject headings, as in "1 work on the subject of Arabic language" or "2 works by 2 authors on the subjects of Jerusalem, Mosques, and Muḥammad". Sometimes the list of subjects is a bit random, especially for manuscripts which contain dozens of works and fragments, but it is curated information and better than nothing.

I've [committed the results](https://github.com/bodleian/fihrist-mss/commit/4b631fcfcb49e837b93650e5ce984a78d0f58763) and loaded them on to the QA site. @ahankinson, @eifionjones: Please take a look and let me know if you want revert it or push it to the production web site.

**Comment by eifionjones** [comment]
This looks good to me - the more useful information in that field the better!

**Comment by andrew-morrison** [comment]
Done. I've also added links for each subject at the bottom of the page to help people find similar manuscripts.
