### ISSUE TITLE
Disambiguate between collection and mss titles

### ISSUE THREAD

**Issue by ahankinson** [bodleian/fihrist-mss#8]
Currently there seems to be a mixing of the `tei:titleStmt/tei:title` field. One some sources it contains the name of the collection, while on others it contains the name of the source. 

The appropriate markup should be to add an `@type=collection` attribute to a second title.

```
<fileDesc>
         <titleStmt>
            <title>MS. Add. A. 10</title>
            <title type="collection">MSS. Add. (Additional) A</title>
...
```

From: https://github.com/bodleian/medieval-mss/blob/master/collections/Add_A/MS_Add_A_10.xml#L5-L6

**NB:** This is particularly critical as the `collection` title is what will be displayed as the collection on the front pages.

**Comment by eifionjones** [comment]
Hi Andrew - as I understood it msIdentifier/institution was going to be the first unit of organisation on the front page? If this is the case, can this be fixed further down the line by the cataloguers themselves?

**Comment by ahankinson** [comment]
Sure; I've updated the QA site to reflect the change. Please have a look and let me know what you think.

**Comment by eifionjones** [comment]
Looks great! Perfect
