### ISSUE TITLE
sourceDesc // idno should have a Shelfmark

### ISSUE THREAD

**Issue by ahankinson** [bodleian/fihrist-mss#9]
`sourceDesc/msDesc/msIdentifier` should have at least one `idno` marked with an `@type=shelfmark` field (or, barring a shelfmark, a list of types of `idno` elements which should be considered as the primary identifier should be supplied. (e.g., if no `@type=shelfmark`, take `@type="catalogue"` or something along those lines)

**Comment by eifionjones** [comment]
For the Fihrist data, there should only be one idno per msIdentifier - I've had a quick look at the data and this should be consistent across the dataset. Do we still need to explicitly identify them with @type?

**Comment by ahankinson** [comment]
OK; I've changed the indexer to choose the first `idno` in the msIdentifier.
